baseURL = "http://localhost:1313/"
languageCode = "en-us"

theme = "hugo-tufte"
title = 'tertium quid'

[params]
  subtitle = "ideas about a post-physicalist paradigm"




uglyURLs = false
	
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

# [[menu.main]]
# name = "Articles"
# url = "/articles/"
# weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4


