---
title: "Declaration of Rights and Freedoms of Dolphins and Whales"
# runningheader: "xxx" # only for pdf output
# subtitle: "yyy" # only for html output

date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
# bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```



Reprinted from [The Dolphin Embassy](https://www.dolphinembassy.org/declaration), November 2017

> Based on a wealth of scientific research and evidence that cetaceans have intellect, feelings, culture and a complex social system;


>Taking into account the growing international movement for the protection of cetaceans;

> Taking into consideration the numerous precedents in this field (national laws on the banning or non-expansion of aquariums, declarations on the recognition of dolphins and whales as non-human individuals, the creation of international marine nature reserves for dolphins and whales);

> Recognizing the vital importance of whales and dolphins for the biosphere of the planet, as well as the danger that human activity poses to them;

> Considering the current stage in the development of human civilization, which requires that humans assume greater responsibility for the planet and for its living systems as a whole;

We declare:

1. All dolphins and whales are individuals possessing self-awareness, intellect and feelings.

2. All dolphins and whales are born and must remain free, they have the right to live and move freely in their natural environment, from which they may not be forcibly removed, and they must not be separated from the family groups to which they belong.

3. The killing of dolphins and whales must be forbidden without exception, their lives cannot be put in danger, and they cannot be treated cruelly.

4. Dolphins and whales cannot be seized, kept in captivity, bought, sold or rented out; they cannot be the property of a state, company or private individual.

5. Dolphins and whales cannot be used for entertainment, medical ends, or military purposes or be subjected to invasive experiments. Any training of dolphins and whales is recognized as a form of slavery.

6. Dolphins and whales have the right to have their culture protected from being interfered with. Observation of dolphins and whales can only take place in natural conditions and should be regulated by international norms that guarantee their peace and security.

7. The fishing industry must comply with legal provisions protecting dolphins and whales from accidentally being caught in nets. It must be held responsible for any pollution of water bodies (including noise pollution) that may threaten the lives and health of dolphins and whales.

8. Regular cargo and passenger vessel routes must circumvent sites that groups of dolphins and whales have chosen as their main habitats.

9. No scientific, educational or other goals can justify making dolphins and whales act under force or holding them in captivity; the only exception to this rule is when and only for the period they require medical aid or must be saved from unavoidable danger; this exception is only valid for the period that such assistance is necessary.

10. The rights and freedoms established by this Declaration should be protected by international and national legislation. Violation of these principles should be equated to crimes against individuals and humanity and should entail legal culpability. 

